# image: "ubuntu"

# before_script:
#   - apt update  && apt install -y  nodejs
#   - node -v
#   - which node

# test:app:
#   script:
#   - node -v
  
  build:

 stage: build

 image: trion/ng-cli

 before_script:

  - npm ci

 script:

  - ng build

 artifacts:

  expire_in: 1 day

  paths:

   - dist/

 tags:

  - docker