TODO :
    - animation look noisy
    - Add stuck/total quantity field to report 
    - verify registered users
    - add more helpfull info to project table
    - add chart dashboard
    - progressive enhancement (notification, badge, bg sync ...)
    - Study web dev practices 
    - enable mongo monit

    - IMP:
        - better i18n support
        - badge of n of new bill on user profile icon
    - FIX:
        # - disable errors until press submit
        - unsubscribe from obs when you finish

IN PROGRESS :


DONE :
    - partial offline support
    - cache google analytics
    - reload bills after payment
    - performance opt
    - remove jquery from bootstrap
    - meta and title for each page
    - robots
    - use html element to store 'typed' data
    - Buil ARIA
    - show units in number input field billForm/projectForm/transactionForm
    - integrate unit into billpdf/projectList/billList
    - add unit to project list
    - add is payed in the bill table 
    - move repeated html to separate components
    - animation
    - beter ux (make password visible on demand)
    - meaning full lablels in buttons
    - Translation pdf and app
    - Collect web vitals
    - Limit img size on desk
    - Add creator field to collections 
    - Hidden field in transaction for projectID
    - A way for use to know he enter negative num in transaction 
    - Autocomplete attr
    - Use units with ng pipes 
    - Use float num ng pipes 
    - focus on reliability and robustness
    - light house suggestion
    - accessibility:
        - check label[for] == input[id]
        - add name to input
        - input[type]
        - check for attr usage
        - required translation
        - change buttons to a on navigation in auth components
        - check button,a,div usage
    - reset forms after success
    - dismiss payment form after success
    - file input is without style
    - remove old angular fa package
    - deprecate angular fa icons and use native ones
    - use URL.revokeObjectURL after you call URL.createObjectURL
    - access any browser api using window
    - remove '?' if no qs
    - strong typed return in services (not obs) to avoid adrifting between server and browser
    - use native types in ts ex ==> string, object ...
    - get user req is not init
    - fix ssr errors
    - translate to arabe
    - define models
    - define home route
    - img problem xss
    - undraw images in forms
    - pagination
    - user profile
    - propagate ui elements throgh out the app [alerts, spinner, error messages, progress bars]
    - show loader as placeholder when data doesnt arrived yet
    - write all conf in host.ts and spread it in env file
    - add pdf of bills add download
    - add payment form to bills form
    - add loader whenever you send some data to server
    - when you register a user redirect to login page
    - show notification on success
    - progress bar to upload file
    - fix file upload bug still show err
    - allow space in name
    - logout button
    - terms and conditions check box
    - connect to db
    - make resource models
    - make basic UI
    - error/feedback messages

POTENTIAL BUGS :
    - change the way we get project id in transaction component
    - the way we get file object on sign up component
    - find a way to bind close modal event to revoke url in bill component

COMPLEMENT :
    - access location
    - terms and conditions page
    - resource res should be of type of models
    - lint and code style
    - dont show form errors on first load
    - gravatar
    - support social media auth
    - captcha
    - make it pretty at the very end
    - support live chat with ws (handled by node)
    - e2e/karma testing
    - ci/branch features
    - online payment (cmi)
    - sms phone verification
    - utms
    - google analytics
    - ads
    - tawk.to
    - amp
    - use unDraw open source illustrations
    - service worker (workbox)
